# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python image from the Docker Hub
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app
COPY pyproject.toml pyproject.toml
COPY LICENSE LICENSE
COPY README.md README.md

# Install uv
RUN pip install uv --no-cache-dir
RUN uv venv
# 激活虚拟环境并设置 PATH
ENV PATH="/app/.venv/bin:$PATH"
# RUN source .venv/bin/activate
# Install main package and dependencies during build
RUN uv pip install -e . Pillow typer==0.15.2  pyright matplotlib kiwisolver fonttools --no-cache-dir

# Copy the requirements file into the container
# COPY requirements.txt .

# Install the dependencies specified in the requirements file
# RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY src /app/src/

# Command to run the server
CMD ["uv", "run", "mcp_clickzetta_server", "--no-prefetch", "--allow_write"]