# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python image from the Docker Hub
FROM python:3.11.6-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
# COPY requirements.txt .

# Install the dependencies specified in the requirements file
# RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY src/ /app/src

# Set environment variables for MySQL (these can be overwritten with `docker run -e`)
ENV CLICKZETTA_service=your_service_endpoint
ENV CLICKZETTA_instance=your_instance
ENV CLICKZETTA_workspace=your_username
ENV CLICKZETTA_schema=your_password
ENV CLICKZETTA_username=your_database
ENV CLICKZETTA_password=your_database
ENV CLICKZETTA_vcluster=your_database
ENV PYTHONPATH=/app/src

# Command to run the server
CMD ["python", "-m", "mcp_clickzetta_server", "--no-prefetch --allow_write"]